import { EnquiryForm } from "@/components/forms/enquiry-form";
import { PageHero } from "@/components/marketing/page-hero";
import { ServiceCard } from "@/components/marketing/service-card";
import { VehicleJourney } from "@/components/vehicle/vehicle-journey";
import { Container, Eyebrow } from "@/components/ui/container";
import { createMetadata } from "@/lib/seo";

export const metadata = createMetadata("Vehicle Diagnostics & Mobile Mechanic Doncaster", "Professional diagnostics, electrical fault finding, mobile mechanic support, repairs and servicing across Doncaster and South Yorkshire.", "/areas/doncaster");

export default function DoncasterAreaPage() { return <><PageHero eyebrow="Doncaster service area" title="Diagnostics, repairs and mobile mechanic support in Doncaster." body="SOB Autofix serves vehicle owners across Doncaster and South Yorkshire through suitable workshop and mobile appointments."><VehicleJourney compact source="area-doncaster" /></PageHero><section className="py-20"><Container><Eyebrow>Popular local services</Eyebrow><h2 className="text-5xl font-extrabold text-[#071127]">Start with the right route for the fault.</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><ServiceCard title="Vehicle diagnostics" body="System scans, evidence-led fault finding and clear next steps." href="/diagnostics/car-diagnostics" /><ServiceCard title="Mobile mechanic" body="Suitable diagnostics and repair work at the vehicle’s location." href="/mobile-mechanic" icon="repair" /><ServiceCard title="Vehicle servicing" body="Scheduled maintenance and vehicle health observations." href="/services/vehicle-servicing" icon="service" /></div></Container></section><section className="bg-[#F4F7FA] py-20"><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><Eyebrow>Local availability</Eyebrow><h2 className="text-4xl font-extrabold text-[#071127]">Doncaster and South Yorkshire coverage.</h2><p className="mt-5 leading-7 text-[#586575]">Mobile coverage and appointment suitability depend on the specific problem and postcode. Send the details for confirmation.</p></div><EnquiryForm type="general" askLocation title="Ask about Doncaster availability" /></Container></section></>; }
