import Image from "next/image";
import { notFound } from "next/navigation";
import { VehicleEditor } from "@/components/admin/vehicle-editor";
import { AdminField } from "@/components/admin/content-editor";
import { createAdminClient } from "@/lib/supabase/server";
import { getSaleVehicle } from "@/lib/sales/repository";
import { deleteSaleVehicleImage, saveSaleVehicle, updateSaleVehicleImage, uploadSaleVehicleImage } from "../../actions";

export default async function EditVehiclePage({ params }: { params: Promise<{ id: string }> }) { const admin = createAdminClient(); if (!admin) notFound(); const { data } = await admin.from("sale_vehicles").select("slug").eq("id", (await params).id).maybeSingle(); if (!data) notFound(); const vehicle = await getSaleVehicle(data.slug); if (!vehicle) notFound(); return <><p className="text-xs font-extrabold tracking-widest text-[#1974E2] uppercase">Vehicle sales</p><h1 className="mb-8 mt-2 text-4xl font-extrabold text-[#071127]">Edit {vehicle.make} {vehicle.model}</h1><VehicleEditor vehicle={vehicle} action={saveSaleVehicle} /><section className="mt-8 rounded-2xl border border-[#E4EAF0] bg-white p-6"><h2 className="text-2xl font-bold text-[#071127]">Vehicle gallery</h2><p className="mt-2 text-sm text-[#667586]">Use genuine vehicle images only. Lower positions appear first.</p><form action={uploadSaleVehicleImage} className="mt-6 grid gap-4 md:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="vehicleId" value={vehicle.id} /><AdminField label="Image"><input name="file" type="file" accept="image/jpeg,image/png,image/webp" required /></AdminField><AdminField label="Alt text"><input name="alt" minLength={5} maxLength={180} required /></AdminField><button className="min-h-12 self-end rounded-xl bg-[#1974E2] px-5 font-bold text-white">Upload image</button></form><div className="mt-7 grid gap-5">{vehicle.images.map((image) => <article key={image.id} className="grid gap-4 rounded-xl border border-[#E4EAF0] p-4 md:grid-cols-[180px_1fr_auto]"><div className="relative aspect-[4/3] overflow-hidden rounded-lg bg-[#E4EAF0]"><Image src={image.url} alt={image.alt} fill sizes="180px" className="object-cover" /></div><form action={updateSaleVehicleImage} className="grid content-start gap-3 sm:grid-cols-[1fr_100px_auto]"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="vehicleId" value={vehicle.id} /><AdminField label="Alt text"><input name="alt" required minLength={5} maxLength={180} defaultValue={image.alt} /></AdminField><AdminField label="Position"><input name="position" type="number" min="0" max="100" required defaultValue={image.position} /></AdminField><button className="min-h-12 self-end rounded-xl bg-[#071127] px-4 text-sm font-bold text-white">Save</button></form><form action={deleteSaleVehicleImage} className="self-center"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="vehicleId" value={vehicle.id} /><button className="min-h-11 rounded-xl border border-red-200 px-4 text-sm font-bold text-red-800">Delete</button></form></article>)}{!vehicle.images.length && <p className="rounded-xl bg-[#F4F7FA] p-5 text-sm text-[#667586]">No approved vehicle images yet.</p>}</div></section></>; }
