import { ArrowRight, BatteryCharging, Check, MapPin, ScanLine, Smartphone, Wrench } from "lucide-react";
import Link from "next/link";
import { JsonLd } from "@/components/seo/json-ld";
import { ServiceCard } from "@/components/marketing/service-card";
import { TrustBar } from "@/components/marketing/trust-bar";
import { VehicleJourney } from "@/components/vehicle/vehicle-journey";
import { ButtonLink } from "@/components/ui/button";
import { Container, Eyebrow } from "@/components/ui/container";
import { areas, contactLinks, diagnostics, services } from "@/config/site";
import { createMetadata, localBusinessJsonLd } from "@/lib/seo";
import { getActiveOffer } from "@/lib/offers/repository";

export const metadata = createMetadata(
  "Professional Diagnostics. Not Guesswork.",
  "Professional vehicle diagnostics, electrical fault finding, repairs, servicing and vehicle sales in Doncaster.",
  "/",
);

export default async function HomePage() {
  const offer = await getActiveOffer();
  return (
    <>
      <JsonLd value={localBusinessJsonLd()} />
      <section className="hero-grid relative overflow-hidden py-16 text-white sm:py-20 lg:py-28">
        <Container className="relative grid items-center gap-12 lg:grid-cols-[1fr_.95fr]">
          <div>
            <Eyebrow className="text-[#67B9FF]">Automotive diagnostics · Doncaster</Eyebrow>
            <h1 className="text-balance text-6xl leading-[.9] font-extrabold sm:text-7xl lg:text-[5.5rem]">Professional Diagnostics.<br /><span className="text-[#168BFF]">Not Guesswork.</span></h1>
            <p className="mt-7 max-w-2xl text-lg leading-8 text-[#C6D2DF]">Automotive diagnostics, electrical fault finding, repairs, servicing and vehicle sales in Doncaster and surrounding areas.</p>
            <div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/book">Book appointment <ArrowRight size={18} /></ButtonLink><ButtonLink href={contactLinks.phone} variant="secondary">Call SOB Autofix</ButtonLink></div>
            <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm text-[#DCE6F2]"><span className="flex items-center gap-2"><Check size={17} className="text-[#67B9FF]" /> Systematic testing</span><span className="flex items-center gap-2"><Check size={17} className="text-[#67B9FF]" /> Mobile appointments</span><span className="flex items-center gap-2"><Check size={17} className="text-[#67B9FF]" /> Doncaster &amp; South Yorkshire</span></div>
          </div>
          <VehicleJourney compact source="homepage" />
        </Container>
      </section>

      <TrustBar />

      <section className="deferred-section py-20 sm:py-28">
        <Container>
          <div className="max-w-3xl"><Eyebrow>What we do</Eyebrow><h2 className="text-balance text-4xl font-extrabold text-[#071127] sm:text-5xl">Start with the fault. Then plan the repair.</h2><p className="mt-5 text-lg leading-8 text-[#586575]">Modern vehicles are interconnected. A warning or fault code points us towards a system; professional testing helps identify what is actually wrong.</p></div>
          <div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">
            <ServiceCard title="Advanced diagnostics" body="Scan relevant systems, analyse evidence and carry out targeted checks." href="/diagnostics" />
            <ServiceCard title="Auto electrical" body="Investigate wiring, sensors, power supplies, drains and communication faults." href="/diagnostics/electrical-fault-finding" icon="diagnostic" />
            <ServiceCard title="Repairs & servicing" body="Clear recommendations followed by approved maintenance and repair work." href="/services" icon="repair" />
            <ServiceCard title="Vehicle sales" body="Browse available used vehicles with honest, vehicle-specific information." href="/cars-for-sale" icon="inspection" />
          </div>
        </Container>
      </section>

      {offer && <section className="bg-[#EAF3FF] py-14"><Container className="flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><Eyebrow>Current service offer</Eyebrow><h2 className="text-3xl font-extrabold text-[#071127]">{offer.title}</h2><p className="mt-2 max-w-3xl leading-7 text-[#586575]">{offer.description}</p></div><ButtonLink href="/services/vehicle-servicing">View servicing</ButtonLink></Container></section>}

      <section className="deferred-section diagnostic-panel py-20 text-white sm:py-28">
        <Container>
          <div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]">
            <div><Eyebrow className="text-[#67B9FF]">Vehicle diagnostics</Eyebrow><h2 className="text-balance text-5xl font-extrabold">A fault code is a starting point—not the answer.</h2><p className="mt-5 text-lg leading-8 text-[#C6D2DF]">We combine system scans with focused electrical and mechanical tests. That means recommendations are based on evidence, not a parts list generated by a scanner.</p><ButtonLink className="mt-8" href="/diagnostics">Explore diagnostics</ButtonLink></div>
            <div className="grid gap-4 sm:grid-cols-2">{diagnostics.filter((item) => item.published).slice(0, 6).map((item) => <ServiceCard key={item.slug} title={item.name} body={item.summary} href={`/diagnostics/${item.slug}`} dark />)}</div>
          </div>
        </Container>
      </section>

      <section className="deferred-section bg-[#F4F7FA] py-20 sm:py-28">
        <Container className="grid items-center gap-12 lg:grid-cols-2">
          <div className="rounded-3xl bg-[#071127] p-8 text-white shadow-2xl sm:p-10"><div className="grid grid-cols-2 gap-4"><Feature icon={<Smartphone />} title="Mobile diagnostics" /><Feature icon={<BatteryCharging />} title="Starting faults" /><Feature icon={<Wrench />} title="Mobile repairs" /><Feature icon={<MapPin />} title="Doncaster areas" /></div></div>
          <div><Eyebrow>Mobile mechanic</Eyebrow><h2 className="text-5xl font-extrabold text-[#071127]">Professional help at your location.</h2><p className="mt-5 text-lg leading-8 text-[#586575]">Tell us where the vehicle is, whether it can be driven and what is happening. We’ll review the request and explain the appropriate next step without promising an unsupported emergency response time.</p><ButtonLink className="mt-8" href="/mobile-mechanic">Request mobile assistance</ButtonLink></div>
        </Container>
      </section>

      <section className="deferred-section py-20 sm:py-28">
        <Container>
          <div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="max-w-2xl"><Eyebrow>Repairs & servicing</Eyebrow><h2 className="text-5xl font-extrabold text-[#071127]">Approved work, clearly explained.</h2></div><Link className="font-bold text-[#1974E2]" href="/services">View all verified services →</Link></div>
          <div className="mt-10 grid gap-5 md:grid-cols-3">{services.filter((item) => item.published).map((item) => <ServiceCard key={item.slug} title={item.name} body={item.summary} href={`/services/${item.slug}`} icon={item.slug === "vehicle-servicing" ? "service" : "repair"} />)}</div>
        </Container>
      </section>

      <section className="deferred-section bg-[#071127] py-20 text-white">
        <Container className="grid gap-10 lg:grid-cols-[1fr_1.1fr]">
          <div><Eyebrow className="text-[#67B9FF]">How it works</Eyebrow><h2 className="text-5xl font-extrabold">From symptom to sensible next step.</h2><p className="mt-5 text-[#C6D2DF]">Share the vehicle and problem first, so the appointment starts with useful context.</p></div>
          <ol className="grid gap-4">{["Identify your vehicle", "Tell us what is happening", "Choose the relevant service", "Book or request an estimate"].map((step, index) => <li key={step} className="flex items-center gap-5 rounded-2xl border border-white/10 bg-white/5 p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#1974E2] font-black">{index + 1}</span><strong className="text-lg">{step}</strong></li>)}</ol>
        </Container>
      </section>

      <section className="deferred-section py-20 sm:py-24">
        <Container className="grid gap-10 lg:grid-cols-[1fr_1.2fr]">
          <div><Eyebrow>Areas covered</Eyebrow><h2 className="text-5xl font-extrabold text-[#071127]">Serving Doncaster and South Yorkshire.</h2><p className="mt-5 leading-7 text-[#586575]">Workshop and mobile availability depends on the service and location. Contact us with the vehicle and postcode to confirm.</p><ButtonLink className="mt-7" href="/areas">View coverage</ButtonLink></div>
          <div className="flex flex-wrap content-start gap-3">{areas.map((area) => <span key={area} className="rounded-full border border-[#1974E2]/20 bg-[#F4F7FA] px-4 py-2 text-sm font-semibold text-[#071127]">{area}</span>)}</div>
        </Container>
      </section>

      <section className="hero-grid py-20 text-white"><Container className="text-center"><ScanLine className="mx-auto mb-5 text-[#67B9FF]" size={44} /><h2 className="text-balance text-5xl font-extrabold">Don’t replace parts based on guesswork.</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-[#C6D2DF]">Identify the fault first. Then make an informed repair decision.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><ButtonLink href="/book">Book diagnostics</ButtonLink><ButtonLink href="/get-a-quote" variant="secondary">Request an estimate</ButtonLink></div></Container></section>
    </>
  );
}

function Feature({ icon, title }: { icon: React.ReactNode; title: string }) {
  return <div className="rounded-2xl border border-[#1974E2]/25 bg-white/5 p-5"><span className="text-[#168BFF]">{icon}</span><strong className="mt-8 block text-lg">{title}</strong></div>;
}
