export const vehicleModelsByMake = {
  "Abarth": ["500", "500C", "595", "695", "124 Spider"],
  "Alfa Romeo": ["Giulia", "Giulietta", "Junior", "MiTo", "Stelvio", "Tonale"],
  "Audi": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "e-tron", "Q2", "Q3", "Q4 e-tron", "Q5", "Q7", "Q8", "R8", "TT"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  "BMW": ["1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series", "7 Series", "8 Series", "i3", "i4", "i5", "i7", "i8", "iX", "iX1", "iX3", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "Z4"],
  "BYD": ["Atto 3", "Dolphin", "Seal", "Seal U"],
  "Chevrolet": ["Aveo", "Camaro", "Captiva", "Corvette", "Cruze", "Matiz", "Orlando", "Spark", "Trax"],
  "Chrysler": ["300C", "Grand Voyager", "PT Cruiser", "Voyager", "Ypsilon"],
  "Citroën": ["Ami", "Berlingo", "C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C5 X", "Dispatch", "DS3", "Grand C4 Picasso", "Relay", "SpaceTourer"],
  "Cupra": ["Ateca", "Born", "Formentor", "Leon", "Tavascan"],
  "Dacia": ["Bigster", "Duster", "Jogger", "Logan", "Sandero", "Sandero Stepway", "Spring"],
  "Daihatsu": ["Charade", "Copen", "Cuore", "Materia", "Sirion", "Terios"],
  "DS Automobiles": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9"],
  "Fiat": ["124 Spider", "500", "500C", "500e", "500L", "500X", "Bravo", "Doblo", "Ducato", "Fiorino", "Grande Punto", "Panda", "Punto", "Scudo", "Tipo"],
  "Ford": ["B-Max", "C-Max", "EcoSport", "Edge", "Explorer", "Fiesta", "Focus", "Galaxy", "Grand C-Max", "Ka", "Ka+", "Kuga", "Mondeo", "Mustang", "Mustang Mach-E", "Puma", "Ranger", "S-Max", "Tourneo Connect", "Tourneo Custom", "Transit", "Transit Connect", "Transit Custom"],
  "Genesis": ["G70", "G80", "GV60", "GV70", "GV80"],
  "Honda": ["Accord", "Civic", "CR-V", "CR-Z", "e", "e:Ny1", "FR-V", "HR-V", "Insight", "Jazz", "NSX", "S2000", "ZR-V"],
  "Hyundai": ["Bayon", "Coupe", "i10", "i20", "i30", "i40", "Ioniq", "Ioniq 5", "Ioniq 6", "ix20", "ix35", "Kona", "Santa Fe", "Tucson", "Veloster"],
  "Infiniti": ["EX", "FX", "G", "M", "Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX70"],
  "Isuzu": ["D-Max", "Rodeo", "Trooper"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "S-Type", "XE", "XF", "XJ", "XK"],
  "Jeep": ["Avenger", "Cherokee", "Compass", "Grand Cherokee", "Patriot", "Renegade", "Wrangler"],
  "Kia": ["Carens", "Ceed", "EV3", "EV6", "EV9", "Niro", "Optima", "Picanto", "ProCeed", "Rio", "Sedona", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "Venga", "XCeed"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["CT", "ES", "GS", "IS", "LBX", "LC", "LS", "NX", "RC", "RX", "RZ", "UX"],
  "Lotus": ["Elise", "Emeya", "Eletre", "Emira", "Evora", "Exige"],
  "Maserati": ["Ghibli", "GranCabrio", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["2", "3", "5", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-30", "MX-5", "RX-8"],
  "Mercedes-Benz": ["A-Class", "B-Class", "C-Class", "CLA", "CLC", "CLK", "CLS", "E-Class", "EQA", "EQB", "EQC", "EQE", "EQS", "G-Class", "GLA", "GLB", "GLC", "GLE", "GLS", "M-Class", "S-Class", "SL", "SLC", "SLK", "Sprinter", "V-Class", "Vito"],
  "MG": ["3", "4", "5", "GS", "HS", "Marvel R", "MG6", "TF", "ZS"],
  "MINI": ["Clubman", "Convertible", "Cooper", "Countryman", "Hatch", "Paceman", "Roadster"],
  "Mitsubishi": ["ASX", "Colt", "Eclipse Cross", "i-MiEV", "L200", "Lancer", "Outlander", "Pajero", "Shogun", "Space Star"],
  "Nissan": ["350Z", "370Z", "Almera", "Ariya", "Cube", "Juke", "Leaf", "Micra", "Murano", "Navara", "Note", "Pathfinder", "Primastar", "Pulsar", "Qashqai", "Townstar", "X-Trail"],
  "Peugeot": ["1007", "107", "108", "2008", "206", "207", "208", "3008", "306", "307", "308", "4007", "407", "5008", "508", "Bipper", "Boxer", "Expert", "Partner", "RCZ", "Rifter"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Boxster", "Cayenne", "Cayman", "Macan", "Panamera", "Taycan"],
  "Renault": ["Arkana", "Austral", "Captur", "Clio", "Espace", "Fluence", "Grand Scenic", "Kadjar", "Kangoo", "Koleos", "Laguna", "Master", "Megane", "Modus", "Rafale", "Scenic", "Symbioz", "Trafic", "Twingo", "Zoe"],
  "Saab": ["9-3", "9-5", "9-7X", "900", "9000"],
  "SEAT": ["Alhambra", "Altea", "Arona", "Arosa", "Ateca", "Exeo", "Ibiza", "Leon", "Mii", "Tarraco", "Toledo"],
  "Škoda": ["Citigo", "Elroq", "Enyaq", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Rapid", "Roomster", "Scala", "Superb", "Yeti"],
  "Smart": ["#1", "#3", "Forfour", "Fortwo", "Roadster"],
  "SsangYong": ["Korando", "Kyron", "Musso", "Rexton", "Rodius", "Tivoli", "Torres"],
  "Subaru": ["BRZ", "Crosstrek", "Forester", "Impreza", "Legacy", "Levorg", "Outback", "Solterra", "Tribeca", "WRX", "XV"],
  "Suzuki": ["Across", "Alto", "Baleno", "Celerio", "Grand Vitara", "Ignis", "Jimny", "Kizashi", "S-Cross", "Splash", "Swift", "SX4", "Vitara"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y"],
  "Toyota": ["Auris", "Avensis", "Aygo", "Aygo X", "bZ4X", "C-HR", "Camry", "Corolla", "GT86", "Hilux", "iQ", "Land Cruiser", "Mirai", "Prius", "Proace", "RAV4", "Supra", "Verso", "Yaris", "Yaris Cross"],
  "Vauxhall": ["Adam", "Agila", "Ampera", "Antara", "Astra", "Cascada", "Combo", "Corsa", "Crossland", "Grandland", "Insignia", "Meriva", "Mokka", "Movano", "Signum", "Tigra", "Vectra", "Vivaro", "Zafira"],
  "Volkswagen": ["Amarok", "Arteon", "Beetle", "Caddy", "California", "Caravelle", "CC", "Crafter", "Eos", "Fox", "Golf", "ID.3", "ID.4", "ID.5", "ID.7", "ID. Buzz", "Jetta", "Passat", "Phaeton", "Polo", "Scirocco", "Sharan", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Touareg", "Touran", "Transporter", "Up"],
  "Volvo": ["C30", "C40", "C70", "EC40", "EX30", "EX40", "EX90", "S40", "S60", "S80", "S90", "V40", "V50", "V60", "V70", "V90", "XC40", "XC60", "XC70", "XC90"],
} as const;

export const vehicleMakes = Object.keys(vehicleModelsByMake).sort((left, right) => left.localeCompare(right, "en-GB"));

export const vehicleSalesOptions = {
  fuelType: ["Petrol", "Diesel", "Petrol Hybrid", "Diesel Hybrid", "Mild Hybrid", "Plug-in Hybrid", "Electric", "Hydrogen", "LPG"],
  transmission: ["Manual", "Automatic", "Semi-Automatic", "CVT", "Single-Speed Electric"],
  engineSize: ["0.6L", "0.7L", "0.8L", "0.9L", "1.0L", "1.1L", "1.2L", "1.3L", "1.4L", "1.5L", "1.6L", "1.7L", "1.8L", "1.9L", "2.0L", "2.2L", "2.3L", "2.4L", "2.5L", "2.7L", "2.8L", "3.0L", "3.2L", "3.5L", "4.0L", "4.2L", "4.4L", "5.0L", "Electric"],
  colour: ["Beige", "Black", "Blue", "Bronze", "Brown", "Gold", "Green", "Grey", "Magnetic Grey", "Maroon", "Orange", "Pink", "Purple", "Red", "Silver", "Turquoise", "White", "Yellow"],
  bodyType: ["Camper", "Chassis Cab", "Convertible", "Coupe", "Estate", "Hatchback", "Minibus", "MPV", "Panel Van", "Pickup", "Saloon", "SUV", "Van"],
} as const;

export type VehicleSalesOptionName = keyof typeof vehicleSalesOptions;
