import { Star } from "lucide-react";
import { PageHero } from "@/components/marketing/page-hero";
import { Container } from "@/components/ui/container";
import { getVisibleReviews } from "@/lib/reviews/repository";
import { createMetadata } from "@/lib/seo";

export async function generateMetadata() { const reviews = await getVisibleReviews(); return reviews.length ? createMetadata("Customer Reviews", "Read verified Google reviews selected for display by SOB Autofix in Doncaster.", "/reviews") : { title: "Reviews", robots: { index: false, follow: true } }; }

export default async function ReviewsPage() {
  const reviews = await getVisibleReviews();
  return <><PageHero eyebrow="Customer reviews" title={reviews.length ? "Genuine feedback from Google." : "Verified reviews will appear here."} body={reviews.length ? "A selected set of genuine Google reviews, with direct source attribution." : "The page remains outside navigation and search indexing until the Google Business Profile and genuine review source are connected."} cta={false} /><section className="relative overflow-hidden py-20"><span className="absolute left-0 top-0 h-px w-1/3 bg-[#1974E2]" aria-hidden="true" /><Container>{reviews.length ? <div className="grid items-start gap-5 md:grid-cols-2 md:[&>*:nth-child(even)]:mt-10">{reviews.map((review, index) => <article key={review.id} className="premium-card rounded-[1.6rem_.35rem_1.6rem_.35rem] border border-[#E4EAF0] bg-white p-6 shadow-sm" data-reveal><div className="flex items-center justify-between"><span className="text-xs font-black tracking-[.16em] text-[#1974E2]">{String(index + 1).padStart(2, "0")}</span><span className="flex items-center gap-1 font-bold text-amber-600"><Star size={16} fill="currentColor" />{review.rating}</span></div><p className="mt-8 text-lg leading-8 text-[#3F4B59]">“{review.text}”</p><div className="mt-6 border-t border-[#E4EAF0] pt-4"><strong className="text-[#071127]">{review.authorName}</strong><a className="ml-3 text-xs font-bold text-[#1974E2]" href={review.sourceUri} target="_blank" rel="noreferrer">View on Google ↗</a></div></article>)}</div> : <div className="text-center"><Star className="mx-auto text-[#1974E2]" size={44} /><h2 className="mt-4 text-3xl font-bold text-[#071127]">Genuine feedback only</h2><p className="mx-auto mt-3 max-w-xl leading-7 text-[#586575]">No placeholder testimonials, ratings or review counts are published.</p></div>}</Container></section></>;
}
