"use client";

import { CheckCircle2, KeyRound, LoaderCircle, ShieldCheck, Smartphone, X } from "lucide-react";
import { useActionState, useState } from "react";
import { Button } from "@/components/ui/button";
import { removeMfaFactor, startMfaEnrollment, verifyMfaEnrollment, type EnrollmentState } from "./actions";

const emptyEnrollment: EnrollmentState = { message: "" };

function Image({ src, alt, width, height }: { src: string; alt: string; width: number; height: number; unoptimized?: boolean }) {
  // Supabase returns a complete transient data URI, so it must not pass through Next image optimisation.
  // eslint-disable-next-line @next/next/no-img-element
  return <img src={src} alt={alt} width={width} height={height} />;
}

export function MfaSecurityPanel({ factorId }: { factorId?: string }) {
  const [setup, setupAction, setupPending] = useActionState(startMfaEnrollment, emptyEnrollment);
  const [verification, verifyAction, verifyPending] = useActionState(verifyMfaEnrollment, emptyEnrollment);
  const [removal, removeAction, removePending] = useActionState(removeMfaFactor, { message: "" });
  const [confirmRemoval, setConfirmRemoval] = useState(false);
  const enrollment = setup.enrollment;
  const qrSrc = enrollment?.qrCode ?? "";

  return (
    <section className="rounded-2xl border border-[#E4EAF0] bg-white p-6 sm:p-7" aria-labelledby="authenticator-heading">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start">
        <div className="flex items-start gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-[#EAF3FF] text-[#1974E2]"><Smartphone size={21} aria-hidden="true" /></span><div><h2 id="authenticator-heading" className="text-xl font-bold text-[#071127]">Authenticator app</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#586575]">Protect your account using Google Authenticator, Microsoft Authenticator, Authy, 1Password or another TOTP-compatible authenticator.</p></div></div>
        <span className={`inline-flex w-fit items-center gap-2 rounded-full px-3 py-1.5 text-xs font-bold ${factorId ? "bg-green-100 text-green-800" : "bg-[#EEF2F6] text-[#586575]"}`}>{factorId && <CheckCircle2 size={15} />}Status: {factorId ? "Enabled" : "Not enabled"}</span>
      </div>

      {factorId ? <div className="mt-6 border-t border-[#E4EAF0] pt-6"><p className="text-sm leading-6 text-[#586575]">Your account requires a verification code when signing in.</p><Button type="button" variant="outline" className="mt-5 border-red-200 text-red-800 hover:bg-red-50" onClick={() => setConfirmRemoval(true)}>Remove authenticator</Button></div>
      : !enrollment ? <form action={setupAction} className="mt-6 border-t border-[#E4EAF0] pt-6">{setup.message && <p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-900">{setup.message}</p>}<Button type="submit" disabled={setupPending}>{setupPending ? <><LoaderCircle size={18} className="animate-spin" />Setting up authenticator…</> : <><ShieldCheck size={18} />Set up authenticator</>}</Button></form>
      : <div className="mt-7 border-t border-[#E4EAF0] pt-7"><div className="flex items-center justify-between gap-4"><h3 className="text-xl font-bold text-[#071127]">Set up authenticator</h3></div><ol className="mt-6 grid gap-6 text-sm leading-6 text-[#344256]"><li><strong className="text-[#071127]">1. Open your authenticator app.</strong></li><li><strong className="text-[#071127]">2. Scan this QR code.</strong><div className="mt-4 w-fit rounded-2xl border border-[#D7E0E9] bg-white p-4"><Image src={qrSrc} width={208} height={208} unoptimized alt="QR code for SOB Autofix admin authenticator setup" /></div><details className="mt-4 max-w-lg rounded-xl bg-[#F4F7FA] p-4"><summary className="cursor-pointer font-bold text-[#1446A5]">Can&apos;t scan the QR code?</summary><p className="mt-3 text-xs font-bold uppercase tracking-wide text-[#667586]">Setup key</p><code className="mt-2 block break-all rounded-lg bg-white p-3 font-mono text-sm font-bold text-[#071127]">{enrollment.secret}</code></details></li><li><strong className="text-[#071127]">3. Enter the 6-digit code generated by your app.</strong><form action={verifyAction} className="mt-4 grid max-w-sm gap-4"><input type="hidden" name="factorId" value={enrollment.factorId} /><label htmlFor="enrollment-code" className="sr-only">Six-digit verification code</label><input id="enrollment-code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required className="min-h-14 rounded-xl border border-[#C9D5E2] px-4 text-center font-mono text-2xl font-black tracking-[0.35em] outline-none focus:border-[#1974E2] focus:ring-4 focus:ring-[#1974E2]/15" />{verification.message && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-900">{verification.message}</p>}<Button type="submit" disabled={verifyPending}>{verifyPending ? <><LoaderCircle size={18} className="animate-spin" />Verifying…</> : "Verify and enable"}</Button></form></li></ol></div>}

      {confirmRemoval && factorId && <div className="fixed inset-0 z-[70] grid place-items-center bg-[#071127]/65 p-5" role="dialog" aria-modal="true" aria-labelledby="remove-mfa-title"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-xl bg-red-50 text-red-700"><KeyRound size={21} /></span><button type="button" onClick={() => setConfirmRemoval(false)} aria-label="Cancel removal" className="grid size-10 place-items-center rounded-full text-[#667586] hover:bg-[#F4F7FA]"><X size={19} /></button></div><h3 id="remove-mfa-title" className="mt-5 text-2xl font-bold text-[#071127]">Remove two-factor authentication?</h3><p className="mt-3 text-sm leading-6 text-[#586575]">Your account will no longer require an authenticator code when signing in.</p>{removal.message && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-900">{removal.message}</p>}<form action={removeAction} className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><input type="hidden" name="factorId" value={factorId} /><Button type="button" variant="outline" onClick={() => setConfirmRemoval(false)}>Cancel</Button><Button type="submit" disabled={removePending} className="bg-red-700 hover:bg-red-800">{removePending ? <><LoaderCircle size={18} className="animate-spin" />Removing…</> : "Remove authenticator"}</Button></form></div></div>}
    </section>
  );
}
